title: Govind Akanksha
logo: /assets/img/headshot_circle.png  # Ensure the path to your logo is correct
remote_theme: pages-themes/architect@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme  # This is required for using remote themes
