title: Govind Akanksha
logo: /assets/img/headshot_circle.png  # Ensure the path to your logo is correct
theme: jekyll-theme-minimal
show_downloads: true
plugins:
  - jekyll-remote-theme  # This is necessary for using remote themes, but only if you're using them.
